### ISSUE TITLE
New Release Checklist - v1.10.0

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#1305]
# Description

This issue is tracking steps to complete a release ensuring all artifacts are correctly produced. This covers both automated tasks and manual tasks.

# Release

Manual steps are instructions that need to be taken in order to have a full release on all associated repos. Validation steps consist of checklist of items to verify, to ensure all reqiuirements and releases have gone without problems and that the correct assets are created needed for the manual steps.

## Intiial Steps

- [x] **Github Release** &mdash; create a new release following the semantic versioning guidelines. The next available version should increase either the Major or Minor version, following the semver recommendations. Patch should be set to `0`. This allows individual languages to publish hotfixes under the same version with new patch. An example version format is `v1.2.0`.
    - [x] Create a new tag with the same name `v[MAJOR].[MINOR].0`
    - [x] Ensure code contributions and commits are included in the release description, either by utilizing the GitHub automatic options or entering them manually.
    - [x] Organize the release notes into the following sections: _Language-Specific Changes_, _SDK-Wide Changes_, _Documentation/Samples_, _Protobuf/gRPC Updates_, _Bugfixes/Minor Improvements_, _Internal Improvements_
    - [x] Confirm documentation of any breaking changes with @fundthmcalculus @geel9 @michaeldboyd

## Validation Steps
- [x] Builds complete successfully
- [x] Release actions complete successfully
- [x] **Assets** &mdash; ensure the following assets have been created by the release actions and are uploaded as assets in the release
    - [x] Debian Package, named `trinsic_X.X.0_amd64.deb`
    - [x] Trinsic CLI tarball (for Homebrew), named `trinsic-cli-X.X.0.tar.gz`
    - [x] Trinsic CLI vendored tarball (for Homebrew), named `trinsic-cli-vendor-X.X.0.tar.gz`
    - [x] Trinsic CLI Microsoft Installer (msi), name `trinsic-cli-X.X.0.msi`
    - [x] Trinsic Java/Kotlin (jar), name `trinsic-services-X.X.0.jar`
- [x] **Package Releases** &mdash; validate if packages have been correctly released
  - [x] golang tag (`go/vX.X.0`)
  - [x] nuget.org
  - [x] npmjs.com
  - [x] pypi.org
  - [x] rubygems.org
  - [x] pub.dev (Dart) - future work, this is not fully implemented

## Post-release Manual Steps

- [x] **Swift Release** &mdash; create new release in associated repository for Swift package at [trinsic-id/sdk-swift](https://github.com/trinsic-id/sdk-swift). The release version in this repo follows a pattern that doesn't include leading `v`. Example release format is `1.2.0`.
- [x] External Tools
  - [x] **Homebrew** &mdash; to create a new tap, follow the instructions at [trinsic-id/homebrew-tap](https://github.com/trinsic-id/homebrew-tap) by making a new PR with the required information. This step depends on a release asset package. TODO: Renovate bot can update this automatically
  - [x] ~**Windows Package Manager** (winget) &mdash; Update PR to the yaml here: https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/trinsic/cli/ This step depends on the Microsoft Installer package.~
  - [x] ~**NixOS** &mdash; done automatically by nixos bot. Periodically verify that package versions haven't fallen behind at https://search.nixos.org/packages in Unstable channel.~
- [x] **Samples** &mdash; if required, code samples at https://github.com/trinsic-id/sdk-examples should be updated to match the version
    - [x] Renovate bot will produce PRs to update all relevant samples with the latest trinsic packages, so this is mostly automatic
    - [x] Update Instruqt demo here: https://github.com/trinsic-id/tutorials/
- [x] Release announced to Trinsic Team

**Comment by tmarkovski** [comment]
Did we tap out (🥁) all outstanding items in this issue and can close it?

**Comment by fundthmcalculus** [comment]
> Did we tap out (🥁) all outstanding items in this issue and can close it?

Good catch. [PR here](https://github.com/trinsic-id/homebrew-tap/pull/47). Once CI pipelines pass, we can close this.
