### ISSUE TITLE
remove todo items in Ruby SDK

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#306]
There are several TODO comments in the Ruby SDK which need removed:
- [x] `search_registry` should return map objects in lieu of protobuf objects
- [x] `invite_participant()` verify contact method is set
- [x] `invitation_status()` onboarding reference id must be set
- [x] Populate the README.md file
