### ISSUE TITLE
New Release Checklist - v1.3.0

### ISSUE THREAD

**Issue by tmarkovski** [Dentity-Development/dentity-ecosystems-sdk#377]
# Description

This issue is tracking steps to complete a release ensuring all artifacts are correctly produced. This covers both automated tasks and manual tasks.

# Release

Manual steps are instructions that need to be taken in order to have a full release on all associated repos. Validation steps consist of checklist of items to verify, to ensure all reqiuirements and releases have gone without problems and that the correct assets are created needed for the manual steps.

# Validation Steps

- [x] Builds complete successfully
- [x] Release actions complete successfully
- [x] **Assets** &mdash; ensure the following assets have been created by the release actions and are uploaded as assets in the release
    - [x] Debian Package, named `trinsic_X.X.0_amd64.deb`
    - [x] Trinsic CLI tarball (for Homebrew), named `trinsic-cli-X.X.0.tar.gz`
    - [x] Trinsic CLI vendored tarball (for Homebrew), named `trinsic-cli-vendor-X.X.0.tar.gz`
- [x] **Package Releases** &mdash; validate if packages have been correctly released
  - [x] Golang tag `go/vX.X.0`
  - [x] nuget.org
  - [x] npmjs.com
  - [x] pypi.org
  - [x] rubygems.org

## Manual Steps

- [x] **Github Release** &mdash; create a new release following the semantic versioning guidelines. The next available version should increase either the Major or Minor version, following the semver recommendations. Patch should be set to `0`. This allows individual languages to publish hotfixes under the same version with new patch. An example version format is `v1.2.0`.
  - [x] Ensure code contributions and commits are included in the release description, either by utilizing the GitHub automatic options or entering them manually.
- [x] **Swift Release** &mdash; create new release in associated repository for Swift package at [trinsic-id/sdk-swift](https://github.com/trinsic-id/sdk-swift). The release version in this repo follows a pattern that doesn't include leading `v`. Example release format is `1.2.0`.
- [x] External Tools
  - [x] **Homebrew** &mdash; to create a new tap, follow the instructions at [trinsic-id/homebrew-tap](https://github.com/trinsic-id/homebrew-tap) by making a new PR with the required information. This step depends on a release asset package.
  - [x] **Windows Package Manager** (winget) &mdash; make an update PR to the yaml here: https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/trinsic/cli/
  - [x] **NixOS** &mdash; TODO: Add details
- [x] **Samples** &mdash; if required, code samples at https://github.com/trinsic-id/sdk-examples should be updated to match the version
- [x] Release announced to Trinsic Team

**Comment by fundthmcalculus** [comment]
External tools:
- [x] winget: https://github.com/microsoft/winget-pkgs/pull/41211
- [x] homebrew: https://github.com/trinsic-id/homebrew-tap/pull/10
- [x] NixOS: @tmarkovski thoughts?

**Comment by tmarkovski** [comment]
We'll have to patch homebrew and winget with 1.3.1 that includes #392

**Comment by fundthmcalculus** [comment]
@tmarkovski ready for me to release 1.3.1 for winget?

**Comment by fundthmcalculus** [comment]
https://github.com/microsoft/winget-pkgs/pull/43343

**Comment by tmarkovski** [comment]
Yes. I've also released it to Homebrew, which also now prints correct version. Still need to do NixOS

**Comment by fundthmcalculus** [comment]
Tag me in the NixOS PR so that I can do it in the future.

**Comment by michaeldboyd** [comment]
Update on NixOS?

**Comment by tmarkovski** [comment]
This seems done https://github.com/NixOS/nixpkgs/pull/158508#event-6023374986

**Comment by fundthmcalculus** [comment]
This is done. Closing the issue.

**Comment by tmarkovski** [comment]
That only took 22 days :)
